// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc2084.CMonster2018.subsystems;

import org.usfirst.frc2084.CMonster2018.RobotMap;
import org.usfirst.frc2084.CMonster2018.commands.*;

import com.ctre.phoenix.motorcontrol.ControlMode;
import com.ctre.phoenix.motorcontrol.can.WPI_TalonSRX;

import edu.wpi.first.wpilibj.Compressor;
import edu.wpi.first.wpilibj.Joystick;
import edu.wpi.first.wpilibj.SpeedController;
import edu.wpi.first.wpilibj.command.Subsystem;
// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=IMPORTS

// END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=IMPORTS


/**
 *
 */
public class IntakeBase extends Subsystem {
	
	
	private final Compressor robotCompressor = RobotMap.robotCompressor;
	public static SpeedController rightIntakeSpark = RobotMap.rightIntakeSpark;
	public static SpeedController leftIntakeSpark = RobotMap.leftIntakeSpark;
	public static WPI_TalonSRX intakeTalon = RobotMap.intakeTalon;
	
	
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTANTS

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTANTS

    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
	
	
	
	public void wheelsIntakeStart() {
		rightIntakeSpark.set(-0.9);
		leftIntakeSpark.set(0.9);
	}
	
	public void wheelsIntakeStop() {
		rightIntakeSpark.set(0);
		leftIntakeSpark.set(0);
	}
	
	public void wheelsOutakeStart() {
		rightIntakeSpark.set(0.5);
		leftIntakeSpark.set(-0.5);
	}
	
	public void wheelsOutakeStop() {
		rightIntakeSpark.set(0);
		leftIntakeSpark.set(0);
	}
	
	public void defaultWheelsGoing() {
		rightIntakeSpark.set(-0.2);
		leftIntakeSpark.set(0.2);
	}
	
	public void defaultWheelsStop() {
		rightIntakeSpark.set(0);
		leftIntakeSpark.set(0);
	}
	
	public void CompressorOn() {
		robotCompressor.setClosedLoopControl(true);
	}
	
	public void intakeFoldUp() {
		intakeTalon.set(-0.4);
	
	}
	
	public void intakeFoldDown() {
		intakeTalon.set(0.4);
	}
	
	
	
	

    @Override
    public void initDefaultCommand() {
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND


        // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND

        // Set the default command for a subsystem here.
        // setDefaultCommand(new MySpecialCommand());
    }

    @Override
    public void periodic() {
        // Put code here to be run every loop

    }

    // Put methods for controlling this subsystem
    // here. Call these from Commands.

}

