// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc2084.CMonster2018;

import edu.wpi.first.wpilibj.CameraServer;
import edu.wpi.first.wpilibj.DriverStation;
import edu.wpi.first.wpilibj.TimedRobot;
import edu.wpi.first.wpilibj.command.Command;
import edu.wpi.first.wpilibj.command.Scheduler;
import edu.wpi.first.wpilibj.livewindow.LiveWindow;
import edu.wpi.first.wpilibj.smartdashboard.SendableChooser;
import edu.wpi.first.wpilibj.smartdashboard.SmartDashboard;

import org.usfirst.frc2084.CMonster2018.PID.ElevatorPID;
import org.usfirst.frc2084.CMonster2018.PID.IntakePID;
import org.usfirst.frc2084.CMonster2018.commands.*;
import org.usfirst.frc2084.CMonster2018.subsystems.*;

import com.kauailabs.navx.frc.AHRS;

/**
 * The VM is configured to automatically run this class, and to call the
 * functions corresponding to each mode, as described in the TimedRobot
 * documentation. If you change the name of this class or the package after
 * creating this project, you must also update the build.properties file in 
 * the project.
 */
public class Robot extends TimedRobot {
	
    Command autonomousCommand;
  // SendableChooser<Command> chooser = new SendableChooser<>();
   //where you actually select
   
    SendableChooser<String> sideChooser = new SendableChooser<>(); 
    //string that you can get that tells you which sendable chooser option you selected

    public static OI oi;
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    public static DriveBase driveBase;
    public static ClimberBase climberBase;
    public static ElevatorBase elevatorBase;
    public static IntakeBase intakeBase;

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS

    boolean initCheck = false;
    
	MiddleToRightSwitch middleToRight = new MiddleToRightSwitch();
	MiddleToLeftSwitch middleToLeft = new MiddleToLeftSwitch();
	
	//ElevatorPID elevatorPID = new ElevatorPID();
	//IntakePID intakePID = new IntakePID();
	
    /**
     * This function is run when the robot is first started up and should be
     * used for any initialization code.
     */
    @Override
    public void robotInit() {
   
        RobotMap.init();
        
        initCheck = true;
        SmartDashboard.putBoolean("DidRobotInit?", initCheck);
       
       //elevatorPID.setSetpoint(0);
       //intakePID.setSetpoint(0);
      
        
        //have strings instead so you can compare them later to find out which option you selected
        sideChooser.addObject("MiddleProgram", "M");
        sideChooser.addObject("LeftProgram", "L");
        sideChooser.addObject("RightProgram", "R");
        sideChooser.addDefault("Default", "M");  //NEED DEFAULT OR ELSE IT WON'T SHOW UP
        SmartDashboard.putData("Auto Side", sideChooser);
        
        
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
        driveBase = new DriveBase();
        climberBase = new ClimberBase();
        elevatorBase = new ElevatorBase();
        intakeBase = new IntakeBase();

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
        // OI must be constructed after subsystems. If the OI creates Commands
        //(which it very likely will), subsystems are not guaranteed to be
        // constructed yet. Thus, their requires() statements may grab null
        // pointers. Bad news. Don't move it.
        oi = new OI();

        // Add commands to Autonomous Sendable Chooser
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=AUTONOMOUS

        //chooser.addDefault("Autonomous Command", new AutonomousCommand());

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=AUTONOMOUS
        
        //chooser.addObject("Middle", autonomousCommand);
       // chooser.addObject("Left", autonomousCommand);
        //chooser.addObject("Right", autonomousCommand);
       
       
        
        CameraServer.getInstance().startAutomaticCapture();
		// starts vision stream to SmartDashboard
        
        
        
            }

    /**
     * This function is called when the disabled button is hit.
     * You can use it to reset subsystems before shutting down.
     */
    @Override
    public void disabledInit(){
    	Robot.driveBase.DisableDriveBase();

    }

    @Override
    public void disabledPeriodic() {
        Scheduler.getInstance().run();
    }

    @Override
    public void autonomousInit() {
       String side = sideChooser.getSelected();
        // schedule the autonomous command (example)
       // if (autonomousCommand != null) autonomousCommand.start();
        
        
        String gameData;
        
        gameData = DriverStation.getInstance().getGameSpecificMessage();
        //get the data from the fms and assign to a variable
       
        
       
        initCheck = true;
        SmartDashboard.putBoolean("DidAutonomousInit?", initCheck);
    	
    	
        
        //nested if statements
        if(side.equals("M")) {
        
        if (gameData.charAt(0) == 'R') {
        	//run one of the command groups to score in the right side of the switch from the middle
        
        	//MiddleToRightSwitch middleToRight = new MiddleToRightSwitch();
        	middleToRight.start();
        	
        }
        
        else if(gameData.charAt(0) == 'L') {
        	//run the command group to score in the left side of the switch from the middle
        	//MiddleToLeftSwitch middleToLeft = new MiddleToLeftSwitch();
        	middleToLeft.start();
        }
        }
        
        if(side.equals("L")) {
        	if (gameData.charAt(0) == 'L') {
        		//run the command group to score in the left side of the switch from the left
        		LeftToLeftSwitch leftSwitch = new LeftToLeftSwitch();
        		leftSwitch.start();
        	}
        	else if (gameData.charAt(1) == 'L') {
        		//run the command group to score in the left side of the scale
        		LeftToLeftScale leftScale = new LeftToLeftScale();
        		leftScale.start();
        	}
        	else {
        		//run the command group to turn into the loading zone from the left side
        		LeftNotToScale leftNot = new LeftNotToScale();
        		leftNot.start();
        	}
        }
        
        if (side.equals("R")) {
        	if (gameData.charAt(0) == 'R') {
        		//run the command group to score in the right side of the switch from the right
        		RightToRightSwitch rightSwitch = new RightToRightSwitch();
        		rightSwitch.start();
        	}
        	else if (gameData.charAt(1) == 'R') {
        		//run the command group to score in the right side of the scale
        		RightToRightScale rightScale = new RightToRightScale();
        		rightScale.start();
        	}
        	else {
        		//run the command group to turn into the loading zone from the right side 
        		RightNotToScale rightNot = new RightNotToScale();
        		rightNot.start();
        	}
        }
        
        
        
    }

    /**
     * This function is called periodically during autonomous
     */
    @Override
    public void autonomousPeriodic() {
        Scheduler.getInstance().run();
       SmartDashboard.putBoolean("Did MiddleToRight run?", middleToRight.isRunning());
       SmartDashboard.putBoolean("Did MiddleToLeftRun?", middleToLeft.isRunning());
    }

    @Override
    public void teleopInit() {
    	
        // This makes sure that the autonomous stops running when
        // teleop starts running. If you want the autonomous to
        // continue until interrupted by another command, remove
        // this line or comment it out.
        if (autonomousCommand != null) autonomousCommand.cancel();
    }

    /**
     * This function is called periodically during operator control
     */
    @Override
    public void teleopPeriodic() {
        Scheduler.getInstance().run();
       
    }
    
    public void testPeriodic() {
		//LiveWindow.run();
		Robot.driveBase.EnableDriveBase();
		Robot.driveBase.DriveAutonomous();
		SmartDashboard.putNumber("AV Distance", RobotMap.AverageDistance);
	}
    
   
}
